language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
  - zip -r spring_boot_jojoldu-webservice * # CodeDeploy는 jar를 인식못해서 zip으로 압축
  - mkdir -p deploy
  - mv spring_boot_jojoldu-webservice.zip deploy/spring_boot_jojoldu-webservice.zip

deploy:
  - provider: s3
    access_key_id:
      secure: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값들
    secret_access_key: $AWS_SECRET_KEY
    bucket: jojoldu-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근
    local_dir: deploy # before_deploy에서 생성한 디렉토리들
    wait-until-deployed: true

# Travis CI 서버의 HOME (같은 의존성은 다음 배포때무터 다시 받지 않기 위함)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
# master 브랜치에 푸시되었을때 수행되는 명령어
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - gusgh3315@gmail.com